#! /bin/bash
set -e -o pipefail


FILENAME="$1"
REMOTE_PATH="$2"
MINIO_API_VERSION="${MINIO_API_VERSION:-S3v4}"
RETENTION="${MINIO_RETENTION:-30d}"


source .colors

clr_green clr_bold  "Uploading $FILENAME to S3"

clr_blue clr_bright "Using $MINIO_SERVER with version $MINIO_API_VERSION"

mc -q --insecure alias set pg "$MINIO_SERVER" "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY" --api "$MINIO_API_VERSION"


clr_blue clr_bright "> mc cp -r $FILENAME $REMOTE_PATH"

mc -q --insecure cp -r "$FILENAME" "$REMOTE_PATH" || { echo "Backup failed"; mc rm "$REMOTE_PATH"; exit 1; }


clr_blue clr_bright "Checking if Expiration rule is set"
prefix=$(basename "$REMOTE_PATH")
bucket=$(dirname "$REMOTE_PATH")
rule_exist=$(mc ilm ls "$REMOTE_PATH" --json | jq  ".config.Rules[] | select(.Filter.Prefix | contains(\"$prefix\"))") || true

if [ -z "$rule_exist" ]
then
    clr_blue "Creating Expiration Rule";
    mc ilm add "$REMOTE_PATH"  --expire-days "30";
else
    clr_blue "Expiration Rule Already exist";
fi

clr_blue "Upload Complete"
