#! /bin/bash
set -e -o pipefail



DB_NAME="$1"
ETCD_ENDPOINTS="$2"
DATE=$(date "$DATE_FORMAT")
FILENAME="$DB_NAME-$DATE"

source .colors

clr_green clr_bold "Running backup-etcd"
etcd-exporter "$FILENAME" "$ETCD_ENDPOINTS"
minio-sender "$FILENAME"  "pg/$MINIO_BUCKET/$DB_NAME/$FILENAME"

