#! /bin/bash
set -e -o pipefail


FILENAME="$1"
ENDPOINTS="$2"

source .colors

clr_green clr_bold  "Dumping etcd to $FILENAME"

clr_blue clr_bright "> etcdctl --endpoints=$ENDPOINTS
                --cert=/data/server.crt
                --cacert=/data/ca.crt
                --key=/data/server.key
                snapshot save $FILENAME"

output=$(etcdctl --endpoints=$ENDPOINTS --cert=/data/server.crt --cacert=/data/ca.crt --key=/data/server.key snapshot save "$FILENAME")

clr_blue "$output"